
var fromTwit = 
      { statuses:
         [ { created_at: 'Sun Mar 27 23:48:56 +0000 2016',
             id: 714237802523791400,
             id_str: '714237802523791360',
             text: 'RT @MissH4FLA: @nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/#!/download/ipad" rel="nofollow">Twitter for iPad</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:48:39 +0000 2016',
             id: 714237730721431600,
             id_str: '714237730721431552',
             text: 'RT @MissH4FLA: @nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:48:11 +0000 2016',
             id: 714237611871707100,
             id_str: '714237611871707138',
             text: 'RT @NormGregory: Bernie Sanders backers demand Washington superdelegates feel the Bern https://t.co/3T4znr76pZ https://t.co/yoXpR4HfD9',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 4,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:45:03 +0000 2016',
             id: 714236824332345300,
             id_str: '714236824332345344',
             text: 'RT @pjmyers24: Not Me Us - Feel The Bern - Bernie Sanders 2016 T-Shirt https://t.co/Zq04AEZTBd',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://andrewritchie.info" rel="nofollow">BernieTweet</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 1,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:43:45 +0000 2016',
             id: 714236496946049000,
             id_str: '714236496946049025',
             text: 'Not Me Us - Feel The Bern - Bernie Sanders 2016 T-Shirt https://t.co/Zq04AEZTBd',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://www.facebook.com/twitter" rel="nofollow">Facebook</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             is_quote_status: false,
             retweet_count: 1,
             favorite_count: 1,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:40:46 +0000 2016',
             id: 714235748560416800,
             id_str: '714235748560416768',
             text: 'RT @MissH4FLA: @nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:39:50 +0000 2016',
             id: 714235512932831200,
             id_str: '714235512932831232',
             text: 'RT @MissH4FLA: @nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:39:25 +0000 2016',
             id: 714235404824809500,
             id_str: '714235404824809472',
             text: 'RT @gideonro: Washington State to its Super Delegates: "You work for us. We want Bernie. Respect us or lose your job." https://t.co/YCso3DL.',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 9,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:38:08 +0000 2016',
             id: 714235084610494500,
             id_str: '714235084610494464',
             text: 'RT @MissH4FLA: @nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://andrewritchie.info" rel="nofollow">BernieTweet</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:37:04 +0000 2016',
             id: 714234816544317400,
             id_str: '714234816544317441',
             text: '@nytimes He\'s making the rounds. The more Americans get to know Bernie Sanders, the more Americans feel the BERN!!!!!!!!',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
             in_reply_to_status_id: 714231921564328000,
             in_reply_to_status_id_str: '714231921564327937',
             in_reply_to_user_id: 807095,
             in_reply_to_user_id_str: '807095',
             in_reply_to_screen_name: 'nytimes',
             user: [Object],
             geo: null,
             coordinates: null,
             place: [Object],
             contributors: null,
             is_quote_status: false,
             retweet_count: 6,
             favorite_count: 12,
             favorited: false,
             retweeted: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:36:42 +0000 2016',
             id: 714234723787280400,
             id_str: '714234723787280384',
             text: '#WAcaucus Bernie Sanders #FEELtheBERN Large White Custom Decal IntlShip  #BLM #dnc #CTL #DEMS https://t.co/kZqopSJADs',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://fanatdecal.com" rel="nofollow">ruby 1.0</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             is_quote_status: false,
             retweet_count: 0,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:21:42 +0000 2016',
             id: 714230946984304600,
             id_str: '714230946984304641',
             text: '#WAcaucus Bernie Sanders #FEELtheBERN Large White Custom Decal IntlShip  #p2 #democrat https://t.co/kZqopSJADs',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://fanatdecal.com" rel="nofollow">ruby 1.0</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             is_quote_status: false,
             retweet_count: 0,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' },

           { created_at: 'Sun Mar 27 23:20:36 +0000 2016',
             id: 714230671141515300,
             id_str: '714230671141515264',
             text: 'RT @NormGregory: Bernie Sanders backers demand Washington superdelegates feel the Bern https://t.co/3T4znr76pZ https://t.co/yoXpR4HfD9',
             entities: [Object],
             truncated: false,
             metadata: [Object],
             source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
             in_reply_to_status_id: null,
             in_reply_to_status_id_str: null,
             in_reply_to_user_id: null,
             in_reply_to_user_id_str: null,
             in_reply_to_screen_name: null,
             user: [Object],
             geo: null,
             coordinates: null,
             place: null,
             contributors: null,
             retweeted_status: [Object],
             is_quote_status: false,
             retweet_count: 4,
             favorite_count: 0,
             favorited: false,
             retweeted: false,
             possibly_sensitive: false,
             lang: 'en' } ],
      search_metadata:
         { completed_in: 0.119,
           max_id: 714237802523791400,
           max_id_str: '714237802523791360',
           query: 'bernie%2C+sanders%2C+bern%2C+feel+since%3A2016-03-25+until%3A2016-03-28',
           refresh_url: '?since_id=714237802523791360&q=bernie%2C%20sanders%2C%20bern%2C%20feel%20since%3A2016-03-25%20until%3A2016-03-28&include_entities=1',
           count: 15,
           since_id: 0,
           since_id_str: '0' } }

console.log(fromTwit.statuses)

