
process.env['TWITTER_CONSUMER_KEY'] = "UaWIqAfAQpVaCVDBH00J4sfRK";
process.env['TWITTER_CONSUMER_SECRET'] = "XvZDvmkbt11JEIoX6mcYjfZm6UbXQVsXekOEjHtzjDYzfDcN63";
process.env['TWITTER_ACCESS_TOKEN_KEY'] = "3168061382-ohkKrBin00UF7rfwYJYGPeGJxpXpo4XHegBN77P";
process.env['TWITTER_ACCESS_TOKEN_SECRET'] = "cmexYA9DJSqq2WJfp79h5d7UylrIq87tXlJHvpHEMDyIO";